### ISSUE TITLE
Build for macos

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/uWebSockets.py#5]
I managed to build and benchmark it on macOS and it runs really fast and well. Much faster than Bjoern. There should be both Linux and macOS binaries on pypi

**Comment by dalisoft** [comment]
For me there error when i tried run example

```bash
❯ python hello.py
Traceback (most recent call last):
  File "hello.py", line 1, in <module>
    import uws
  File "/usr/local/lib/python3.7/site-packages/uws/__init__.py", line 2, in <module>
    import uws.uwebsocketspy
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/uws/uwebsocketspy.so, 2): no suitable image found.  Did find:
	/usr/local/lib/python3.7/site-packages/uws/uwebsocketspy.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/usr/local/lib/python3.7/site-packages/uws/uwebsocketspy.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```

### Info

```bash
❯ python -V
Python 3.7.6
```

```bash
❯ pip -V
pip 20.0.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
```

### Snippet

```python3
import uws

app = uws.App()

def httpGet(res, req):
	res.end("Sorry, no HTTP for you this time")

app.get("/*", httpGet)

def wsMessage(ws, message, isBinary):
	ws.send(message)

app.ws("/*", {
	"maxPayloadLength": 1024,
	"message": wsMessage
});

def listenHandler():
    print("Listening to port 3000")

app.listen(3000, listenHandler)
```

**Comment by alexhultman** [comment]
As per the issue, there is no macOS build yet. That's the point of this issue

**Comment by dalisoft** [comment]
Sorry then. When will be available, i can test it =)

**Comment by alexhultman** [comment]
There is now a package for both Linux and macOS

**Comment by dalisoft** [comment]
Wow, it works. Thanks
